---
title: "Media"
---

----

## IASCL Media Coordinator

In January 2023 I became the Media Coordinator for the [IASCL](https://www.childlanguage.org/) (International Association for the Study of Child Language). I take care of the IASCL website as well as social media sites, including pages on [Facebook](https://www.facebook.com/InternationalAssociationForTheStudyOfChildLanguage), [Instagram](https://www.instagram.com/iascl_childlang/), [BlueSky](https://bsky.app/profile/iasclchildlang.bsky.social), and [LinkedIn](https://www.linkedin.com/company/iascl/). I also conduct video interviews with child language researchers that can be found on our [YouTube channel](https://www.youtube.com/@childlanguage).

# Blogs

I've written about the ManyBabies-AtHome project for the International Association for the Study of Child Language (IASCL) blog series, titled [Collecting child language data online using eye-tracking](https://www.childlanguage.org/blog/ly8fs3g7bz8h17h7dregyfqvt3ozu1).

[Cogtales](https://cogtales.wordpress.com/), is "a blog by young female cognitive scientists" that I've contributed to, writing a guide for [writing effective introductory emails](https://cogtales.wordpress.com/2017/01/13/how-to-write-effective-introductory-emails/).

# Media Articles

I've appeared in articles for various awards I've been given or to be recognized as an alumnus.

Together with my collaborator, [Christina Bergmann](https://sites.google.com/site/chbergma/), our meta-analysis on infant mispronunciation sensitivity won the Berkeley Initiative for Transparency in the Social Sciences (BITSS) MetaLab challenge calling for meta-analyses on cognitive development. [Read more](https://www.bitss.org/2018/07/24/metalab-awards-three-contribution-challenge-prizes/)

My alma mater, the University of Wisconsin - Green Bay, has written a few articles about me, both [generally](https://news.uwgb.edu/featured/alumni/05/30/alumni-rising-research-sparks-international-career-for-von-holzen/) and specifically in the [College of Arts, Humanities, and Social Sciences](https://cahsseffect.org/featuredalumni/featured-alum-katie-von-holzen/) and [Psychology Department](https://blog.uwgb.edu/uwgbpsych/featured-alumnus-katie-von-holzen/).

In 2010, I won a [Graduate Scholarship from the Phi Eta Sigma National Honor Society](https://news.uwgb.edu/log-news/releases/05/11/graduate-scholarship-1081/) to support my graduate studies in Göttingen, Germany.

In 2009, I won a [Summer Research Grant from the Psi Chi Honor Society](https://www.psychologicalscience.org/observer/apspsi-chi-summer-research-grant-winners#.WNqK42-GOUk) to work at Dartmouth College.

