---
title: "Searching for a PhD student"

---

----

The department of German Linguistics, with a focus on German as a second/foreign language,  at the TU Dortmund University is advertising a position for a research associate. This is a temporary position, salary level TV-L E13, 50% for the next 3 years and enables the pursuit of a PhD. The candidate will work closely with Dr. Katie Von Holzen (https://kvonholzen.github.io/) and Prof. Dr. Sarah Schimke (http://www.schimke.germanistik.tu-dortmund.de/cms/de/home/Mitarbeiter/Professorin/Schimke.html).

[Read the official advertisement in German.](https://service.tu-dortmund.de/documents/18/2120797/w30-20_FK15_1+Stelle+als+wiss.+Besch._E13+TV-L+50%25+befristet+f%C3%BCr+die+Dauer+von+3+Jahren.pdf/61c9ff7d-0852-9414-9c98-)

Applications from persons of all genders and nationalities are encouraged. Candidates with disabilities will be preferred if equally qualified.

----


## We are looking for someone with:
* a Masters degree in German linguistics or a similar field.
* interest in psycholinguistics research in the areas of language acquisition and multilingualism, especially lexical processing in early foreign language acquisition.
* high work ethic, good communication skills, and who is a team player.
* skills and potential for independent/self-motivated work.
* interest in completing a PhD.
* (optional) experience in empirical research, for example an empirical thesis in psycholinguistics

## Duties:
* Teaching in German linguistics (2 SWS/credit hours)
* Empirical research in psycholinguistics, multilingualism, and language acquisition
* Active participation in administrative activities

## We offer:
* a good research infrastructure in an innovative environment with a motivated, interdisciplinary, and international team

----

## How to apply

Interested candidates should send their applications (Letter of Motivation, CV, Certificates, scientific writing sample-Masters thesis) by April 9th, 2020 with Reference Number **w30-20** by post and email:

Email: sarah.schimke@tu-dortmund.de

and

Post:
<br>Technische Universität Dortmund
<br>Fakultät Kulturwissenschaften
<br>Univ.-Prof. Dr. Sarah Schimke
<br>Professurfür Linguistik des Deutschen:
<br>Schwerpunkt Deutsche als Fremdsprache/Deutsch als Zweitsprache
<br>Emil-Figge-Straße 50
<br>44227 Dortmund
<br>Germany

----

Questions should be directed to Prof. Sarah Schimke
<br>Tel.: 0231 755-2921
<br>E-Mail:sarah.schimke@tu-dortmund.de

We look forward to your application!