---
title: "Projects"
---

----

# Best Practices in Language Acquisition Research

I am committed to ensuring that best practices are used in the field of language acquisition and have demonstrated this commitment through several different avenues, including pioneering a new analysis of time course data, a meta-analysis, and participation in a large-scale collaboration of language acquisition laboratories. 

My study investigating simultaneous acitvation in bilingual toddlers (Von Holzen & Mani, 2012) was the first to apply a non-parametic permutation clusters analysis in the language acquisition field, where my role was adapting the analysis to my own data and subsequently promoting this analysis with other language acquisition researchers. This analysis captures important differences in the timing of effects across a time course while controlling for the false-alarm rate. 

In completing the meta-analysis of mispronunciation sensitivity development, my role was tabulating over two decades of research and analyzing the results with meta-analytic models. This provides an essential integration of research on mispronunciation sensitivity in early language acquisition and gives future researchers the tools to plan their own mispronunciation sensitivity studies. My co-author, Christina Bergmann, and I have already produced a conference proceedings paper based on this meta-analysis (Von Holzen & Bergmann, 2018) and the full manuscript should be submitted by the end of this year. 

Finally, I participated in the Many Babies 1 project, which is the first-ever large-scale collaboration of language acquisition laboratories around the world, with the goal of assessing the robustness of the methods used to examine different phenomenon in language acquisition. My role in the Many Babies 1 project was adapting and testing the collaborative experiment in our lab. Testing for the Many Babies 1 project finished in 2018 and the full manuscript should be published soon.


# The Role of Consonants and Vowels in Lexical Processing

During lexical processing, more weight is often given to consonants than vowels. This pattern has been found in adult speakers of all languages tested thus far, leading to the proposal that humans have a bias for consonants during lexical prosessing (C-bias). Cross-linguistic and developmental evidence suggests that this C-bias may be acquired through early linguistic experience. My postdoctoral work focused on the acoustic/phonetic and lexical factors that drive this emergence during early language acquisition in French-learning infants. Our findings favor an interpretation of C-bias emergence guided by acoustic/phonetic factors, but show that early sensitivity to both consonants and vowels is related to general lexical development over the first two years of life. Although some of the research from this project is already published, the remaining studies should be submitted for publication over the coming year.


# The Nature of Bilingual Lexical Processing Across the Lifespan

Bilinguals must often navigate a linguistic environment that requires them to use only one of their languages. Yet, evidence of connections between the bilingual’s two languages suggest that lexical entries from the other language are active and ready to be accessed, even when the language itself is not currently being used. My dissertation work extended previous findings with evidence that even when completing a task in their first language (L1), bilingual adults activate the labels for objects in both of their languages (Von Holzen & Mani, 2014). I also demonstrated that young bilingual toddlers also activate both languages simultaneously, providing the first evidence of this phenomenon in bilingual children this young (Von Holzen & Mani, 2012). These bilingual toddlers are also sensitive to the phonological overlap between their two languages, which impacts their word recognition (Von Holzen, Fennell, & Mani, 2019). The results suggest that connections between a bilingual’s two languages are evident across the lifespan. Moreover, these findings have generated considerable scientific interest: groups in several other countries are currently working to replicate and extend them. 
