---
title: "Publications"
output: html_document
---


```{r setup_publications, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, tidy = TRUE, message = FALSE, error = FALSE)
library(RefManageR)
```

# Published Manuscripts

```{r}

BibOptions(check.entries = FALSE, bib.style = "authoryear", style = "text")

bib <- c(BibEntry(
  bibtype = "article", 
  key = "VonHolzen2018", 
  year = "2018", 
  title = "Consonant and vowel processing in word form segmentation: An infant ERP study",
  author = "Katie Von Holzen and Leo-Lyuki Nishibayashi and Thierry Nazzi", 
  journaltitle = "Brain Sciences", 
  number = "24", 
  volume = "8", 
  pages = "1-15"),
BibEntry(
  bibtype = "article", 
  key = "VonHolzen2019",
title = "The impact of cross-language phonological overlap on bilingual and monolingual toddlers' word recognition", 
year = "2019", 
author = "Katie Von Holzen and C. T. Fennell and Nivedita Mani", 
journaltitle = "Bilingualism: Langauge and Cognition",
number = "3", 
volume = "22", 
pages = "476-499"))

WriteBib(bib, file = "cv/references.bib", biblatex = TRUE,
append = FALSE, verbose = TRUE)


```


