---
title: "Research Interests"
bibliography: References.bib
csl: apa-6th-edition.csl
---

----

# DoyouunderstandwhatIamsaying? How learners break into speech segmentation

In my Habilitation project, I study how foreign language learners approach word segmentation (parse incoming speech into individual words) before they have been exposed to or started instruction in that language. The goal of this project is to understand how foreign language input can be modified to ease learning, and how we can improve learning situations and educational approaches for L2 and foreign language (FL) learning. One strain focuses on whether similarity with the learners' L1 influences their word segmentation. For example, young English-learning children can recognize words in German that are sound similar to their translation equivalent in English (e.g. shoe - Schuh), even without any German experience. This suggests a role of L1 form overlap in initial foreign-language acquisition. I study this further in the German Research Foundation funded grant that I am co-PI (216,325 €) on with Prof. Holger Hopp *Ini-Seg: Initial foreign speech segmentation in school-aged children*. In one of the *Ini-Seg* projects, we examine how such L1 form overlap influences initial word segmentation abilities in 1st and 2nd grade German primary school students, before they have received English foreign-language instruction [@IniSegLexTransparency]. In the other Ini-Seg project, we found that although these young learners are able to segment words, this ability is modulated by their phonological awareness skills, yet not local phonotactic L1 similarity [@IniSegPhonotactics]. Within the Ini-Seg project I mentored a PhD student (Marie Schnieders) and a postdoctoral researcher (Sophia Wulfert). 
 
A second strain studies how modifications to the speech input may especially encourage foreign language learning. When we speak with language learners, we modify our speech, whether we are addressing infants (infant-directed speech, IDS) or adults (foreigner-directed speech, FDS), but we know little of whether these modifications support uptake in FL and L2 learners. For example, adult English speakers can more easily segment and later recognize words when they first encountered them in speech produced in IDS [@AdultIDSADS]. I have also presented the results of a preliminary study which finds a clear advantage for IDS, but intermediate findings for FDS that require further study [@iVH2025b; @tVH2025a]. 

Please read more about the *Ini-Seg* project [here](https://www.tu-braunschweig.de/en/anglistik/seminar/linguistik/forschung/ini-seg).



# Open and Collaborative approaches to language acquisition Research

I study early language and cognitive development using a global, collaborative, open science approach. As a member of the leadership committee of the [ManyBabies-AtHome project](https://manybabies.org/MB-AtHome/), I work to reduce the WEIRD (Western, Educated, Industrialized, Rich, Democratic) bias by both building a resource-friendly and accessible, open-source toolkit for online eye-tracking experiments as well as establishing a research network to study diverse study populations [@tV2022b; @tV2022a]. In the Word Recognition sub-project, which is funded by an HK 3.0 grant awarded to my collaborator Prof. Eon-Suk Ko at Chosun University (South Korea), I manage a diverse team of international researchers as we design a massively cross-linguistic experiment (10+ languages) to study word recognition over the second year of life [@pVH2022a]. I also contributed to the first ManyBabies initiative [@MB1] and am a collaborator in Many Babies 5, which examines the Hunter and Ames model of infant looking preference [@MB5]. I firmly believe that such global, collaborative approaches are essential for the field of early language development.

My study investigating simultaneous acitvation in bilingual toddlers [@VonHolzen2012] was the first to apply a non-parametic permutation clusters analysis in the language acquisition field, where my role was adapting the analysis to my own data and subsequently promoting this analysis with other language acquisition researchers ([see my Tutorials](https://kvonholzen.github.io/Macquarie_Presentation_buddy.html)). This analysis captures important differences in the timing of effects across a time course while controlling for the false-alarm rate. 

In completing the meta-analysis of mispronunciation sensitivity development, my role was tabulating over two decades of research and analyzing the results with meta-analytic models. This provides an essential integration of research on mispronunciation sensitivity in early language acquisition and gives future researchers the tools to plan their own mispronunciation sensitivity studies. This meta-analysis with my co-author, Christina Bergmann, is published in *Developmental Psychology* [@MetaAnalysis]. A preprint and the open data and code can be found [here](https://osf.io/rvbjs/).


# The Role of Consonants and Vowels in Lexical Processing

During lexical processing, more weight is often given to consonants than vowels. This pattern has been found in adult speakers of all languages tested thus far, leading to the proposal that humans have a bias for consonants during lexical prosessing (C-bias). Cross-linguistic and developmental evidence suggests that this C-bias may be acquired through early linguistic experience [@Nazzi2016]. My postdoctoral work focused on the acoustic/phonetic and lexical factors that drive this emergence during early language acquisition in French-learning infants. Our findings favor an interpretation of C-bias emergence guided by acoustic/phonetic factors, but show that early sensitivity to both consonants and vowels is related to general lexical development over the first two years of life [@VonHolzen2018; @VonHolzen2020; @CVaccent].

# The Nature of Bilingual Lexical Processing Across the Lifespan

Bilinguals must often navigate a linguistic environment that requires them to use only one of their languages. Yet, evidence of connections between the bilingual’s two languages suggest that lexical entries from the other language are active and ready to be accessed, even when the language itself is not currently being used. My dissertation work and subsequent work extends previous findings with evidence that even when completing a task in their first language (L1), bilingual adults activate the labels for objects in both of their languages [@VonHolzen2014; @Basque]. I also demonstrated that young bilingual toddlers also activate both languages simultaneously, providing the first evidence of this phenomenon in bilingual children this young [@VonHolzen2012]. These bilingual toddlers are also sensitive to the phonological overlap between their two languages, which impacts their word recognition [@VonHolzen2019]. The results suggest that connections between a bilingual’s two languages are evident across the lifespan. Moreover, these findings have generated considerable scientific interest: groups in several other countries are currently working to replicate and extend them. 

# References