---
title: "Teaching"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup_teaching, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, tidy = TRUE, message = FALSE, error = FALSE)
library(vitae)
library(scholar)
library(papaja)
library(tibble)
library(stringr)

```

----

## Philosophy

As a teacher, I understand my role to be that of a guide. I know the way (learning outcome) and I know at least one way to get there (my own way), but it is my job to accompany the students as they find their own way through their learning process. In this regard, I especially focus on the student as an individual and understand that each student comes to my class with their own needs, wants, skills, and interests. I therefore try to create my classes such that all learners can be successful, integrating sections where I give information, sections that encourage discussion or interaction amongst the students, and sections where students need to apply what they’ve learned to a task. My approach to teaching has been informed by teaching lectures and seminars in Linguistics (TU Dortmund, TU Braunschweig) and Hearing and Speech Sciences (University of Maryland) departments, giving methods and statistics tutorials ([see my Tutorials](https://kvonholzen.github.io/Tutorials.html)) as well as participating in professional development initiatives, such as the teaching certificate program “Professional Teaching Competence for Higher Education” or the various workshops of the University of Maryland’s Teaching and Learning Transformation Center. I use this experience to continually strive to develop excellent teaching skills, as evidences by my current average student evaluation rating of 1.2 (excellent).

## Resources and Materials

### QALMRI Framework

Starting with the course "Should I Buy That? Comparing Media Claims with Scientific Evidence from Brain & Behavior Research", which I taught as an [I-Series course](https://gened.umd.edu/i-series/iseries.html) to incoming freshman at the University of Maryland (and which was conceptualized by [Jared Novick](https://hesp.umd.edu/facultyprofile/novick/jared)), I began using the QALMRI Framework to guide students through reading primary, scientific articles ([Brosowsky & Parshina, 2017](https://pdfs.semanticscholar.org/3bed/03eae99d886c3c7967419d3d3cfcb132b1ee.pdf)). The QALMRI Framework stands for:

 * Q: Question
 * A: Alternatives
 * L: Logic
 * M: Methods
 * R: Results
 * I: Inferences
 
and teaches students how to identify the questions being asked in the scientific article as well as how those questions are answered and the consequences of those answers. I've since used this approach in a seminar class on bilingualism taught at the Master level at the TU Dortmund. In this class, I found it particularly helpful in preparing students to summarize existing research and create an approach to answering their own research questions (Forschungskonzept).

----

## Teaching Experience

### Lecture-based Courses

<br>**Should I Buy That? Comparing Media Claims with Scientific Evidence from Brain & Behavior Research**
<br>Bachelor students
<br>Department of Hearing and Speech Sciences
<br>University of Maryland
<br>2018
<br>
<br>**Experimental Methods for Testing Language Comprehension**
<br>Bachelor students
<br>German Department
<br>Georg-August-Universität Göttingen
<br>2012
<br>


### Seminars

<br>**First Language Acquisition**
<br>Bachelor students
<br>English Department
<br>Technische Universität Braunschweig
<br>2024 - present
<br>
<br>**Introduction to Linguistics**
<br>Bachelor students
<br>English Department
<br>Technische Universität Braunschweig
<br>2023 - present
<br>
<br>**Phonetics and Phonology**
<br>Bachelor students
<br>English Department
<br>Technische Universität Braunschweig
<br>2022 - present
<br>
<br>**Listening in the L1 and L2**
<br>Bachelor students
<br>English Department
<br>Technische Universität Braunschweig
<br> 2022 - 2024
<br>
<br>**Wortsegmentierung: Erkenntnisse aus der Psycho- und Neurolinguistik (Word segmentation: Findings from Psycho- and Neurolinguistics)**
<br>Master students
<br>German Department
<br>Technische Universität Dortmund
<br> 2021 - 2022
<br>
<br>**Zwei Sprachen, ein Gehirn: Bilingualismus und dessen Konsequenzen (Two Languages, One Mind: Bilingualism and its Consequences)**
<br>Master students
<br>German Department
<br>Technische Universität Dortmund
<br>2019 - 2021
<br>
<br>**Einführung in die Sprachwissenschaft (Introduction to Linguistics)**
<br>Bachelor students
<br>German Department
<br>Technische Universität Dortmund
<br>2019 - 2022
<br>
<br>**Language Acquisition and Processing**
<br>Bachelor students
<br>German Department
<br>Georg-August-Universität Göttingen
<br>2012
<br>

<br>

### Tutorials

Some resources from these tutorials can be found under the [Tutorials](Tutorials.html) tab.


<br>**Setting up and analyzing an eye-tracking experiment: From Open Sesame to Eyelink to R**
<br>Doctoral students, postdoctoral researchers, and faculty
<br>Université Paris Descartes
<br>2017
<br>
<br>**Time Course Analysis in R**
<br>Doctoral students, Research Training Group 2070
<br>Georg-August-Universität Göttingen
<br>2017
<br>
<br>**EEG Pre-processing and Analysis Using EEGLAB and ERPLAB**
<br>Doctoral students, postdoctoral researchers, and faculty
<br>Université Paris Descartes
<br>2016
<br>

----

